plugins {
    alias libs.plugins.android.application
    alias libs.plugins.devtools.ksp
    alias libs.plugins.hilt.android
    alias libs.plugins.kotlin.compose
    alias libs.plugins.kotlin.serialization
}

def gitCommitCount = Integer.parseInt('git rev-list --count HEAD'.execute([], project.rootDir).text.trim())

android {
    compileSdk = 36

    defaultConfig {
        applicationId 'me.gm.cleaner.plugin'
        minSdk 29
        targetSdk = 36
        versionCode gitCommitCount
        versionName 'beta12'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        multiDexEnabled false
        resourceConfigurations += ['en', 'zh-rCN', 'zh-rTW']
    }

    signingConfigs {
        release {
            if (System.getenv("SIGNING_KEY_STORE")) {
                storeFile file(System.getenv("SIGNING_KEY_STORE"))
                storePassword System.getenv("SIGNING_KEY_STORE_PASSWORD")
                keyAlias System.getenv("SIGNING_KEY_ALIAS")
                keyPassword System.getenv("SIGNING_KEY_PASSWORD")
                v1SigningEnabled true
                v2SigningEnabled true
                enableV3Signing true
                enableV4Signing true
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (System.getenv("SIGNING_KEY_STORE")) {
                signingConfig signingConfigs.release
            } else {
                signingConfig signingConfigs.debug
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        aidl true
        buildConfig true
        compose true
    }
    lint {
        checkDependencies true
    }
    namespace 'me.gm.cleaner.plugin'
    externalNativeBuild {
        cmake {
            path "src/main/jni/CMakeLists.txt"
            version "3.22.1"
        }
    }
}

dependencies {
    compileOnly libs.libxposed.api
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.lifecycle.runtime.compose

    // Compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.material.icons.extended
    implementation libs.androidx.activity.compose
    implementation libs.androidx.navigation.compose
    implementation libs.androidx.hilt.navigation.compose
    implementation libs.androidx.compose.runtime.livedata
    implementation libs.accompanist.drawablepainter
    implementation libs.accompanist.permissions
    annotationProcessor libs.androidx.room.compiler
    ksp libs.androidx.room.compiler
    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.runtime
    implementation libs.androidsvg
    implementation libs.glide
    ksp libs.glide.ksp
    implementation libs.com.google.android.material
    implementation libs.gson
    implementation libs.hilt.android
    ksp libs.hilt.android.compiler
    implementation libs.retrofit
    implementation libs.retrofit.converter.gson
    implementation libs.retrofit.converter.scalars

    implementation libs.markwon.core
    implementation libs.markwon.ext.strikethrough
    implementation libs.markwon.html
    implementation libs.markwon.image.glide
    implementation libs.appiconloader
    implementation libs.appiconloader.glide

    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.serialization.json
    implementation libs.hiddenapibypass

    debugImplementation libs.leakcanary.android
}
